# -*- coding: utf-8 -*-
"""simbio_mocando_dados_estruturados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHaYnvj7ZeVieQxqbQ6yivuKscmcjcQp
"""

# pip install faker

import pandas as pd
import numpy as np
from faker import Faker
import random

url = "https://docs.google.com/spreadsheets/d/19TgjwZfvaOcaETbQpmyWGwcpbEBAZ01P/export?format=csv"
df_original = pd.read_csv(url)
df_original.head()

df_original

fake = Faker('pt_BR')

"""PARÂMETROS E LISTAS DE ATRIBUTOS"""

# areas = [
#     "Financeiro", "Tecnologia", "RH", "Marketing", "Operações",
#     "Contabilidade", "Jurídico", "Educação", "Saúde", "Vendas",
#     "Logística", "Engenharia", "Produto", "Atendimento",
#     "TI Infraestrutura", "Design", "Pesquisa", "Serviços Gerais",
#     "Gestão Pública", "Consultoria", "TI Suporte", "Agronegócio",
#     "Manufatura"
# ]

areas = {
    "Financeiro": [
        "Analista Financeiro", "Controller", "Tesoureiro", "Analista de Custos",
        "Coordenador Financeiro", "Assistente Financeiro", "Analista de Riscos"
    ],
    "Tecnologia": [
        "Desenvolvedor", "Analista de Dados", "Engenheiro de Software",
        "Cientista de Dados", "DevOps", "Arquiteto de Software",
        "Engenheiro de IA"
    ],
    "RH": [
        "BP RH", "Recrutador", "Generalista de RH", "Analista de Treinamento",
        "Coordenador de RH", "Especialista em Cultura", "Psicólogo Organizacional"
    ],
    "Marketing": [
        "Analista de Marketing", "Growth", "Social Media", "Copywriter",
        "Gestor de Tráfego Pago", "Marketing Analytics", "Gerente de Marca"
    ],
    "Operações": [
        "Coordenador de Operações", "Analista de Processos",
        "Supervisor Operacional", "Gestor de Projetos", "Analista Lean",
        "Especialista Kaizen"
    ],
    "Contabilidade": [
        "Contador", "Assistente Contábil", "Analista Fiscal",
        "Gerente Contábil", "Consultor Tributário", "Analista de Auditoria"
    ],
    "Jurídico": [
        "Advogado", "Assistente Jurídico", "Paralegal",
        "Advogado Trabalhista", "Advogado Tributário"
    ],
    "Educação": [
        "Professor", "Instrutor", "Pedagogo", "Coordenador Pedagógico",
        "Tutor", "Professor Universitário"
    ],
    "Saúde": [
        "Enfermeiro", "Técnico de Enfermagem", "Auxiliar Clínico",
        "Fisioterapeuta", "Psicólogo", "Nutricionista", "Médico Clínico"
    ],
    "Vendas": [
        "Vendedor", "Gerente Comercial", "Representante",
        "Executivo de Contas", "Closer", "Pré-vendas (SDR)"
    ],
    "Logística": [
        "Analista Logístico", "Coordenador de Logística", "Supervisor de Frota",
        "Analista de PCP", "Gestor de Armazém"
    ],
    "Engenharia": [
        "Engenheiro Civil", "Engenheiro Mecânico", "Engenheiro Elétrico",
        "Técnico em Projetos", "Engenheiro de Produção"
    ],
    "Produto": [
        "Product Owner", "Product Manager", "Analista de Produto",
        "Pesquisador de Produto"
    ],
    "Atendimento": [
        "Atendente", "Analista de Suporte", "Supervisor de Atendimento",
        "Customer Success"
    ],
    "TI Infraestrutura": [
        "Analista de Redes", "Analista de Infraestrutura",
        "Administrador de Sistemas"
    ],
    "Design": [
        "Designer Gráfico", "Designer UI", "Designer UX",
        "Diretor de Arte", "Ilustrador"
    ],
    "Pesquisa": [
        "Pesquisador", "Analista de Inteligência de Mercado",
        "Cientista Social", "Estatístico"
    ],
    "Serviços Gerais": [
        "Auxiliar de Limpeza", "Zelador", "Porteiro"
    ],
    "Gestão Pública": [
        "Gestor Público", "Analista de Políticas Públicas"
    ],
    "Consultoria": [
        "Consultor de Negócios", "Consultor Estratégico",
        "Consultor Financeiro"
    ],
    "TI Suporte": [
        "Suporte N1", "Suporte N2", "Analista de Atendimento Técnico"
    ],
    "Agronegócio": [
        "Técnico Agrícola", "Engenheiro Agrônomo", "Analista Agro"
    ],
    "Manufatura": [
        "Operador de Máquinas", "Supervisor Industrial",
        "Analista de Produção", "Engenheiro de Processos"
    ]
}

qualidades_lista = [
    "Empatia", "Organização", "Comunicação", "Criatividade",
    "Pensamento Crítico", "Liderança", "Flexibilidade", "Colaboração",
    "Tomada de Decisão", "Trabalho Sob Pressão", "Proatividade",
    "Visão Sistêmica", "Inteligência Emocional", "Persistência",
    "Resiliência", "Foco em Resultados", "Disciplina", "Curiosidade",
    "Capacidade Analítica", "Ética", "Responsabilidade",
    "Adaptabilidade", "Escuta Ativa", "Autoconfiança",
    "Empreendedorismo"
]

defeitos_lista = [
    "Ansiedade", "Procrastinação", "Dificuldade em delegar",
    "Perfeccionismo", "Apressado", "Indecisão", "Teimosia",
    "Autocrítica Excessiva", "Dificuldade em Dizer Não",
    "Falta de Paciência", "Impulsividade", "Insegurança",
    "Rigidez", "Falar Demais", "Ser Crítico Demais",
    "Esquecer Detalhes", "Dificuldade em Pedir Ajuda",
    "Falta de Assertividade"
]

"""FUNÇÃO PARA GERAR REGISTROS FAKE
Operação para gerar texto de experiência coerente com a área e o emprego do registro
"""

def gerar_texto_experiencia(area, emprego):
    anos = random.randint(1, 25)
    return f"{emprego} por {anos} anos"


# Gera os registros
def gerar_registros_fake(qtd):
    registros = []

    for _ in range(qtd):
        area = random.choice(list(areas.keys()))
        emprego = random.choice(areas[area])

        registros.append({
            "nome": fake.name(),
            "idade": random.randint(21, 60),
            "area": area,
            "emprego": emprego,
            "qualidades": ", ".join(random.sample(qualidades_lista, 3)),
            "defeitos": ", ".join(random.sample(defeitos_lista, 2)),
            "texto": gerar_texto_experiencia(area, emprego)  # <-- coerente
        })

    return pd.DataFrame(registros)

"""CARREGAR BASE EXISTENTE"""

caminho_base_original = "base_pessoas_para_ML.xlsx"

try:
    df_original = pd.read_excel(caminho_base_original)
    print("Base original carregada!")
except:
    df_original = pd.DataFrame()
    print("Nenhuma base original encontrada — criando tudo do zero.")

"""GERAR NOVOS REGISTROS"""

novos_registros = 30
df_novos = gerar_registros_fake(novos_registros)

df_novos

df_novos.to_excel('base_pessoas_para_ML_faker.xlsx', index=False)